package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

type initConfig struct {
	Domain   string
	Scope    []string
	SeedUser string
	SeedPass string
	SeedHash string
	Profile  string
}

var initCfg initConfig

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate an adpack.yaml config in the current directory",
	Long: `Creates a minimal adpack.yaml configuration file with target
details, scope, seed credentials, and evasion profile.

Run without flags for interactive prompts:
  adpack init

Or pass flags for non-interactive:
  adpack init --domain corp.local --seed-user jsmith --seed-pass 'Password1'`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := promptMissing(); err != nil {
			return err
		}

		cfg := map[string]interface{}{
			"domain":  initCfg.Domain,
			"profile": initCfg.Profile,
		}
		if len(initCfg.Scope) > 0 {
			cfg["scope"] = initCfg.Scope
		}
		if initCfg.SeedUser != "" || initCfg.SeedPass != "" || initCfg.SeedHash != "" {
			seed := map[string]string{
				"user":     initCfg.SeedUser,
				"password": initCfg.SeedPass,
				"hash":     initCfg.SeedHash,
				"domain":   initCfg.Domain,
			}
			cfg["seeds"] = []map[string]string{seed}
		}

		data, err := yaml.Marshal(cfg)
		if err != nil {
			return fmt.Errorf("marshal config: %w", err)
		}

		header := "# adpack.yaml — generated by adpack init\n# Edit this file to customize your target.\n\n"
		full := header + string(data)

		if err := os.WriteFile("adpack.yaml", []byte(full), 0644); err != nil {
			return fmt.Errorf("write adpack.yaml: %w", err)
		}

		fmt.Println("[+] adpack.yaml created")
		fmt.Println()
		fmt.Println("  Next, run: adpack autorun")
		fmt.Println()
		return nil
	},
}

func promptMissing() error {
	if initCfg.Domain == "" {
		fmt.Print("Target domain (e.g. corp.local): ")
		fmt.Scanln(&initCfg.Domain)
	}
	if initCfg.Profile == "" {
		initCfg.Profile = "native"
	}
	if len(initCfg.Scope) == 0 {
		fmt.Print("Target subnet (e.g. 10.0.0.0/24) [optional]: ")
		var s string
		fmt.Scanln(&s)
		if s != "" {
			initCfg.Scope = []string{s}
		}
	}
	if initCfg.SeedUser == "" {
		fmt.Print("Seed username (e.g. jsmith) [optional]: ")
		fmt.Scanln(&initCfg.SeedUser)
	}
	if initCfg.SeedUser != "" && initCfg.SeedPass == "" && initCfg.SeedHash == "" {
		fmt.Print("Seed password [optional]: ")
		fmt.Scanln(&initCfg.SeedPass)
	}
	return nil
}

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().StringVar(&initCfg.Domain, "domain", "", "Active Directory domain")
	initCmd.Flags().StringSliceVar(&initCfg.Scope, "scope", nil, "CIDR ranges (comma-separated)")
	initCmd.Flags().StringVar(&initCfg.SeedUser, "seed-user", "", "Seed credential username")
	initCmd.Flags().StringVar(&initCfg.SeedPass, "seed-pass", "", "Seed credential password")
	initCmd.Flags().StringVar(&initCfg.SeedHash, "seed-hash", "", "Seed credential NTLM hash")
	initCmd.Flags().StringVarP(&initCfg.Profile, "profile", "p", "native", "Evasion profile")
}
